- name: configtest apachectl
  shell: "apachectl configtest"
  register: rlt
  check_mode: no
  changed_when: false
  when: not ansible_check_mode

- name: httpd restart
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  when:
    not ansible_check_mode and "'Syntax OK' in rlt.stderr"
